### ISSUE TITLE
Cannot download label

### ISSUE THREAD

**Issue by derDeno** [SoCuul/Bambu-LabelGen#6]
I tried your tool and I cannot download a label.
The console output is the following:

```
DOMException: Failed to execute 'querySelector' on 'Document': '[object PointerEvent]' is not a valid selector.
    at t4 (https://bambu-labelgen.socuul.dev/assets/index-xJeZaC5a.js:35:89128)
    at Un (https://bambu-labelgen.socuul.dev/assets/index-xJeZaC5a.js:13:39)
    at Ft (https://bambu-labelgen.socuul.dev/assets/index-xJeZaC5a.js:13:118)
    at HTMLButtonElement.n (https://bambu-labelgen.socuul.dev/assets/index-xJeZaC5a.js:17:7098)
```

**Comment by SoCuul** [comment]
Hi! Just fixed this in the latest version. Should be deployed on the domain, but if it's not working for you, just try clearing your browser cache.
